# Configuration client exemple (alice.conf)

[Interface]
PrivateKey = ExampleClientPrivateKey
Address = 10.8.0.2/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = ExampleServerPublicKey
Endpoint = <IP_PUBLIC_VPS>:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25